version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ecommerce_seller_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: ecommerce_seller
    ports:
      - "5433:5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
