version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: meesho-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meesho
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - meesho-network

  redis:
    image: redis:alpine
    container_name: meesho-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data   # <-- Redis persistence
    networks:
      - meesho-network

networks:
  meesho-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
